server:
  port: 8080
  servlet.context-path: "/"
  error.include-message: always

logging:
  level:
    org.springframework: info

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}
          jwk-set-uri: ${JWT_SET_URI}
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  # H2 TEST DATABASE
  datasource:
    url: "jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1"
    driverClassName: org.h2.Driver
    username: "sa"
    password: ""
